# Q1. Import numpy as np and print the version number.

In [1]:
import numpy as np

In [4]:
print(np.__version__)

1.19.2


# Q2. Create a 1D array of numbers from 0 to 19 with step difference 2

In [25]:
x = np.arange(1,20,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Q3. Create a 3×3 numpy array of all False’s value

In [26]:
y = np.full((3,3),False,dtype = bool)

In [27]:
y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Q4. Extract all Even numbers from array?

In [31]:
arrEven = np.arange(2,21,2)

In [32]:
arrEven

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Q5. Replace all odd numbers in arr with -1

In [41]:
replOdd = np.arange(10)

In [42]:
replOdd[replOdd % 2 == 1] = -1

In [43]:
replOdd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q6. Replace all odd numbers in arr with -1 without changing arr

In [44]:
rplOddArr = np.arange(10)

In [45]:
rplOddArr = np.where((rplOddArr % 2 == 1),-1,rplOddArr)

In [46]:
rplOddArr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q7. Convert a 1D array to a 2D array with 2 rows

In [55]:
convArr = np.arange(10)

In [57]:
arr_2d = np.reshape(convArr, (2, 5))

In [58]:
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Q8. Stack arrays a and b vertically

In [65]:
arr_a = np.arange(10).reshape(2,-1)
arr_b = np.repeat(1,10).reshape(2,-1)
print(arr_a)
print(arr_b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [66]:
np.concatenate([arr_a, arr_b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Q9. Stack the arrays a and b horizontally.

In [68]:
arr_a = np.arange(10).reshape(2,-1)
arr_a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
arr_b = np.repeat(3,10).reshape(2,-1)
arr_b

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [74]:
np.concatenate([arr_a,arr_b],axis=1)

array([[0, 1, 2, 3, 4, 3, 3, 3, 3, 3],
       [5, 6, 7, 8, 9, 3, 3, 3, 3, 3]])

# Q10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [82]:
a_Pattern = np.array([1,2,3])

a_Pattern


array([1, 2, 3])

In [80]:
np.r_[np.repeat(a_Pattern, 3), np.tile(a_Pattern, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Q11. Get the common items between a and b

In [83]:
arr_a = np.array([2,3,5,4,3,6,7,8,4,3])
arr_b = np.array([4,3,6,7,4,3,2,6,7,2])
np.intersect1d(arr_a,arr_b)

array([2, 3, 4, 6, 7])

# Q12. From array a remove all items present in array b

In [84]:
arr_a = np.array([2,3,5,4,3,6,7,8,4,3])
arr_b = np.array([4,3,6,7,4,3,2,6,7,2])
np.setdiff1d(arr_a,arr_b)

array([5, 8])

# Q13. Get the positions where elements of a and b match

In [114]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([1,2,3,5,7,3,5])

np.where(a == b)

(array([0, 1, 2], dtype=int64),)

# Q14. Get all items between 5 and 10 from a.

In [115]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

# Q15. Convert the function maxx that works on two scalars, to work on two arrays.



In [116]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# Q16. Swap columns 1 and 2 in the array arr.

In [117]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# Q17. Swap rows 1 and 2 in the array arr:

In [122]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# Q18. Reverse the rows of a 2D array arr.

In [125]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# Q19. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [127]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [128]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))


In [129]:
rand_arr

array([[5.36553689, 5.04410588, 5.85161278],
       [5.67125015, 6.87121655, 5.74971122],
       [5.82648727, 8.2176122 , 5.55149135],
       [7.65806452, 7.56364179, 6.83006373],
       [8.7495807 , 9.52579249, 8.57872852]])

# Q20. Reverse the columns of a 2D array arr.

In [131]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
arr[::,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Q21. Print or show only 3 decimal places of the numpy array rand_arr.



In [136]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.91292202, 0.07860086, 0.05174758],
       [0.68723553, 0.54769052, 0.24392512],
       [0.74460734, 0.47802324, 0.15703403],
       [0.61618676, 0.27216767, 0.05226392],
       [0.48864861, 0.366877  , 0.80763756]])

In [138]:
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.913, 0.079, 0.052],
       [0.687, 0.548, 0.244],
       [0.745, 0.478, 0.157],
       [0.616, 0.272, 0.052]])

# Q22. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [141]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [143]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# Q23. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [145]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [146]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# Q24. Print the full numpy array a without truncating.



In [153]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [157]:
import sys
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Q25. Manual construction of arrays 1D array and its diminsion and shape?

In [160]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [161]:
a.ndim

1

In [163]:
a.shape

(4,)

In [165]:
len(a)

4

# Q26. Manual construction of arrays 2D array and its diminsion,shape and Length?

In [167]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
b.ndim

2

In [169]:
b.shape

(2, 3)

In [171]:
len(b)  # returns the size of the first dimension

2

# Q27. Manual construction of arrays 2D array and its diminsion,shape and Length?

In [175]:
c = np.array([[[1,2,3], [2,4,5]], [[3,6,7], [4,7,8]]])
c

array([[[1, 2, 3],
        [2, 4, 5]],

       [[3, 6, 7],
        [4, 7, 8]]])

In [176]:
c.shape

(2, 2, 3)

In [178]:
c.ndim

3

In [179]:
len(c)

2

# Q28. using Common arrays to print zero array 3 by 3?

In [180]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Q29.using eye() function, to print an array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one?

In [181]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q30.using diag() function, to print an array where all elements are equal to zero, except for the k-th diagonal, whose values are greater or equal to one?

In [182]:
d = np.diag(np.array([1, 2, 3, 4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Q31.reversing  array sequence?

In [184]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Q32. Copies and views Operation in array?

In [186]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
b = a[::]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q33.Convert Degrees Into Radians?


In [192]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
x

array([1.570796, 3.141593, 4.712389, 6.283185])

# Q34.Convert Radians to Degrees?

In [193]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
x

array([ 90., 180., 270., 360.])

# Q35.Finding hypotenues using pythagoras theorem in NumPy?

In [194]:
base = 3
perp = 4
x = np.hypot(base, perp)
x

5.0

# Q36.numpy.random.rand() function creates an array of specified shape and fills it with random values?

In [195]:
a = np.random.rand(1,10)
a

array([[0.575093, 0.891322, 0.209202, 0.185328, 0.108377, 0.219697,
        0.978624, 0.811683, 0.171941, 0.816225]])

# Q37. numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution

In [196]:
a = np.random.randn(1,20)
a

array([[-0.501413, -1.658703, -1.007577, -0.508734,  0.781488, -0.654381,
         0.041172, -0.201917, -0.870813,  0.228932, -0.40804 , -0.103925,
         1.567179,  0.497025,  1.155872,  1.838612,  1.535727,  0.254998,
        -0.844157, -0.982943]])

# Q38.np.random.ranf returns an array of specified shape and fills it with random floats in the half-open interval 

In [197]:
a = np.random.ranf(20)
print(a)

[0.852395 0.975006 0.884853 0.359508 0.598859 0.354796 0.34019  0.178081
 0.237694 0.044862 0.505431 0.376252 0.592805 0.629942 0.1426   0.933841
 0.94638  0.602297 0.387766 0.363188]


# Q39.This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

In [198]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([8, 7, 6, 0, 1, 5, 3, 9, 2, 4])

# Q40. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [199]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [200]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# Q41.numpy.mean() Compute the arithmetic mean (average) of the given data (array elements) along the specified axis.

In [201]:
x = np.array([10,20,30,40,5])
x

array([10, 20, 30, 40,  5])

In [202]:
np.mean(x)

21.0

# Q42.numpy.cumsum Return the cumulative sum of the elements along a given axis?

In [203]:
x = np.array([10,20,30,40,5])
x

array([10, 20, 30, 40,  5])

In [204]:
np.cumsum(x)

array([ 10,  30,  60, 100, 105], dtype=int32)

# Q43.numpy.nancumprod Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one. The cumulative product does not change when NaNs are encountered and leading NaNs are replaced by ones.

In [206]:
x = np.array([10,20,30,40,5])
x

array([10, 20, 30, 40,  5])

In [207]:
x.cumprod()

array([     10,     200,    6000,  240000, 1200000], dtype=int32)

# Q44.numpy.sum Sum of array elements over a given axis?

In [209]:
np.sum([0.5, 1.5])

2.0

# Q45.numpy.unique Find the unique elements of an array?


In [210]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

# Q46.numpy.save Save an array to a binary file in NumPy .npy format.?

In [213]:
x = np.arange(10)
np.save("outfile", x)

In [214]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q47.numpy.savez Save several arrays into a single file in uncompressed .npz ?

In [215]:
from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(10)
y = np.sin(x)

In [216]:
np.savez(outfile, x, y)

In [217]:
_ = outfile.seek(0) # Only needed here to simulate closing & reopening file
npzfile = np.load(outfile)
npzfile.files

['arr_0', 'arr_1']

In [218]:
npzfile['arr_0']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
npzfile['arr_1']

array([ 0.      ,  0.841471,  0.909297,  0.14112 , -0.756802, -0.958924,
       -0.279415,  0.656987,  0.989358,  0.412118])

# Q48.numpy.array2string Return a string representation of an array?

In [220]:
x = np.array([1e-16,1,2,3])
np.array2string(x, precision=2, separator=',',suppress_small=True)

'[0.,1.,2.,3.]'

# 49.numpy.set_printoptions These options determine the way floating point numbers, arrays and other NumPy objects are displayed?

In [221]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

# 50.numpy.load Load arrays or pickled objects from .npy, .npz or pickled files?

In [224]:
loadx = np.load('outfile.npy')
loadx

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])